
import os


HERE = os.path.abspath(__file__)

BASE_DIR = os.path.abspath(os.path.join(HERE, os.pardir, os.pardir, os.pardir))

SCRIPTS = os.path.join(BASE_DIR, 'bin')

TEMPLATES = os.environ['TEMPLATES_FOLDER']

BROKER_HOST_NAME = os.environ.get('BROKER_HOST_NAME')

DEFAULT_CRAWL_DEPTH = 2


# Configurations that are related to the corpus and its data storage
# DATA_ROOT is the path to the directory that will store corpora and data
# generated by rmxbot
DATA_ROOT = os.environ.get('DATA_ROOT')

# the tmp directory used by rmxbot when processing files, etc...
# TMP_DATA_DIR = '/data/tmp'
TMP_DATA_DIR = os.environ.get('TMP_DATA_DIR')

EXTRACTXT_ENDPOINT = os.environ.get('EXTRACTXT_ENDPOINT')

EXTRACTXT_FILES_UPLOAD_URL = '{}/upload-files'.format(EXTRACTXT_ENDPOINT)

# The path to the directory where corpora along with matrices are stored.
CORPUS_ROOT = os.path.join(DATA_ROOT, 'container')
TEXT_FOLDER = 'text'
MATRIX_FOLDER = 'matrix'

CORPUS_MAX_SIZE = 400

# DATABASE configuration - MONGODB
MONGODB_NAME = os.environ.get('DATABASE_NAME')
# MONGODB_LOCATION = '127.0.0.1'

MONGODB_LOCATION = os.environ.get('MONGODB_LOCATION')
MONGODB_PORT = 27017
MONGODB_USER = os.environ.get('DATABASE_USERNAME')
MONGODB_PASS = os.environ.get('DATABASE_PASSWORD')

# names given to the mongodb collections
DATA_COLL = 'data'
IMAGE_COLL = 'image'
CORPUS_COLL = 'corpus'
CLUSTER_COLL = 'cluster'


CRAWL_MONITOR_COUNTDOWN = 3

CRAWL_MONITOR_MAX_ITER = 150

REQUEST_MAX_RETRIES = 5
